### ISSUE TITLE
一直卡在等待播放器加载完毕

### ISSUE THREAD

**Issue by tang-bai** [xrervip/AutoYuketangforHIT#5]
C:\Users\Administrator\OneDrive - 薅羊毛大学\Desktop\AutoYuketangforHIT-master>py -3.8 run.py
run.py:316: DeprecationWarning: use options instead of chrome_options
  self.driver = webdriver.Chrome(chrome_options=chrome_options)

DevTools listening on ws://127.0.0.1:57634/devtools/browser/92634fb0-d3ed-4d6d-8e29-460ce6a72582
成功配置chrome驱动
成功读取配置文件：./config.json
未指定cookie，需要手动登录雨课堂
未登录。请您扫码登录雨课堂，然后按回车键继续……[20428:5064:0901/015702.756:ERROR:device_event_log_impl.cc(214)] [01:57:02.755] USB: usb_service_win.cc:389 Could not read device interface GUIDs: 系统找不到指定的文件。 (0x2)

登录成功！
成功登录雨课堂
当前课程ID：$7490228$
检测到校验位，已从历史记录中获取链接
全部链接已就绪
https://cejlu.yuketang.cn/pro/lms/420002/7490228/video/11569848
正在播放:01外交及其宗旨
任务进度：完成度：7%
该视频需要播放，尝试加速播放
等待播放器加载完毕
Traceback (most recent call last):
  File "run.py", line 385, in <module>
    AutoYuketangForHIT(mode)
  File "run.py", line 85, in __init__
    self.play_video_list('url_list.txt')
  File "run.py", line 99, in play_video_list
    self.play_video(url)
  File "run.py", line 131, in play_video
    self.wait_and_get_element_text(XPATH_VIDEO_PLAYER)
  File "run.py", line 360, in wait_and_get_element_text
    element = self.wait_element_path_loaded(element_xpath)
  File "run.py", line 340, in wait_element_path_loaded
    element = WebDriverWait(self.driver, 20).until(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

C:\Users\Administrator\OneDrive - 薅羊毛大学\Desktop\AutoYuketangforHIT-master>pause

**Comment by decisive-strike** [comment]
> C:\Users\Administrator\OneDrive - 薅羊毛大学\Desktop\AutoYuketangforHIT-master>py -3.8 run.py
> run.py:316: DeprecationWarning: use options instead of chrome_options
> self.driver = webdriver.Chrome(chrome_options=chrome_options)
> 
> DevTools listening on ws://127.0.0.1:57634/devtools/browser/92634fb0-d3ed-4d6d-8e29-460ce6a72582
> 成功配置chrome驱动
> 成功读取配置文件：./config.json
> 未指定cookie，需要手动登录雨课堂
> 未登录。请您扫码登录雨课堂，然后按回车键继续……[20428:5064:0901/015702.756:ERROR:device_event_log_impl.cc(214)] [01:57:02.755] USB: usb_service_win.cc:389 Could not read device interface GUIDs: 系统找不到指定的文件。 (0x2)
> 
> 登录成功！
> 成功登录雨课堂
> 当前课程ID：$7490228$
> 检测到校验位，已从历史记录中获取链接
> 全部链接已就绪
> https://cejlu.yuketang.cn/pro/lms/420002/7490228/video/11569848
> 正在播放:01外交及其宗旨
> 任务进度：完成度：7%
> 该视频需要播放，尝试加速播放
> 等待播放器加载完毕
> Traceback (most recent call last):
> File "run.py", line 385, in
> AutoYuketangForHIT(mode)
> File "run.py", line 85, in **init**
> self.play_video_list('url_list.txt')
> File "run.py", line 99, in play_video_list
> self.play_video(url)
> File "run.py", line 131, in play_video
> self.wait_and_get_element_text(XPATH_VIDEO_PLAYER)
> File "run.py", line 360, in wait_and_get_element_text
> element = self.wait_element_path_loaded(element_xpath)
> File "run.py", line 340, in wait_element_path_loaded
> element = WebDriverWait(self.driver, 20).until(
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
> raise TimeoutException(message, screen, stacktrace)
> selenium.common.exceptions.TimeoutException: Message:
> 
> C:\Users\Administrator\OneDrive - 薅羊毛大学\Desktop\AutoYuketangforHIT-master>pause

老哥这玩意能用了吗？
